apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://192.168.49.1:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://192.168.49.1:3306/foodcataloguedb
  # foodcataloguedb_url: jdbc:mysql://mysql-db-instance.c2sqiztf28ne.eu-west-2.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db-instance.c2sqiztf28ne.eu-west-2.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:codedecode@atlas-cluster.mqdj7js.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://192.168.49.2
  

  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  