server:
  port: 9091

spring:
  profiles:
    active: local

  application:
    name: RESTAURANT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect